### ISSUE TITLE
merge: Proposal: rename merge to sdmerge

### ISSUE THREAD

**Issue by djspiewak** [slamdata/devtools#24]
`merge` is a very generic name, and it's pretty common to have custom local workflows built around personal scripts like that.  I propose we rename the script from `merge` to `sdmerge` so it's easier to have it on the PATH (e.g. using direnv) without causing conflicts.

**Comment by sellout** [comment]
If only `$PATH` had aliased imports …

**Comment by djspiewak** [comment]
Probably exists in zsh…
