### ISSUE TITLE
merge: default to repo of the current directory

### ISSUE THREAD

**Issue by sellout** [slamdata/devtools#7]
Make it easier to run the merge script when you’re already in a clone of the repo (or a clone of a fork).

**Comment by djspiewak** [comment]
@sellout So I actually think this is a bad idea (and not necessary if we implement #22) because we don't want to mutate the current working HEAD pointers, since there may be outstanding work.  Can I close this as invalid?

**Comment by sellout** [comment]
This isn’t to _use_ the current directory, but simply to be able to type `merge 1234` instead of `merge quasar-analytics/quasar 1234` when you’re in a working copy with `quasar-analytics/quasar` as its upstream.

**Comment by djspiewak** [comment]
Oh even better.  :+1: to that then
